# Generated by Django 4.2.13 on 2026-05-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='manufacture_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Указание года из маркировки или документов (опционально)', null=True, verbose_name='Год изготовления'),
        ),
    ]
