# Generated by Django 4.2.13 on 2026-05-09 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepairTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('in_progress', 'В работе'), ('waiting_parts', 'Ожидание запчастей'), ('resolved', 'Решён'), ('closed', 'Закрыт')], default='open', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('description', models.TextField(verbose_name='Описание дефекта')),
                ('defect_type', models.CharField(blank=True, max_length=100, verbose_name='Тип дефекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Решён')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_tickets', to='assets.asset', verbose_name='Актив')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='employees.employee', verbose_name='Исполнитель')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Зарегистрировал')),
            ],
            options={
                'verbose_name': 'Заявка на ремонт',
                'verbose_name_plural': 'Заявки на ремонт',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RepairWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_description', models.TextField(verbose_name='Описание работ')),
                ('parts_used', models.TextField(blank=True, verbose_name='Использованные запчасти')),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата выполнения')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_works', to='employees.employee', verbose_name='Исполнитель')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='maintenance.repairticket', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Запись о работе',
                'verbose_name_plural': 'Журнал работ',
                'ordering': ['-performed_at'],
            },
        ),
    ]
